name = "Create Horizons"
author = "TM4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97e84d643a2cfc2b02183b6c7afe4b5e5b2e85f16719034b1e41e2fca7135568"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
